---
  - name: install spurtcommerce
    hosts: all
    become: true
    tasks:
      - name: Install required softwares for spring petclinic
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
        with_items:
          - openjdk-11-jdk
          - maven
          - git
